name_ = 'Hello There' ; 
myGui = uifigure('Position', [200 200 800 653], ...
    'Tag', ['SM_', name_], ...
    'Resize', 'off', ...
    'Name', ['Configure Signal Manipulation of Instance: ', name_], ...
    'KeyPressFcn', @keyPressed, ...
    'Visible', 'on', ...
    'CloseRequestFcn', @closeFcn);

function keyPressed()
    disp('Pressed a Key.')
end

function closeFcn()
    disp('I have to close now.')
end
